add test for getJettonData getWalletData getMaxPunishment
HipoFinance/contract pull request #7
Opened 2023-10-02 16:23 UTC by MKdir98

This PR is for https://github.com/HipoFinance/contract/issues/3
My telegram ID: [MK_dir98](https://t.me/MK_dir98)

2023-10-07 14:04 UTC, behrang requested changes

2023-10-07 14:04 UTC, behrang commented on tests/Getter.spec.ts
Rename the file to 'Getters' so it matches the `describe` function.

2023-10-07 14:04 UTC, behrang commented on tests/Getter.spec.ts
> +    it('should getters work', async () => {
Use separate test for each getter and improve names. For example, 'should return maxPunishment`, 'should return Jetton data', 'should return wallet data' etc.

Also, please add tests for other get methods like `get_treasury_state` and `get_wallet_state` and check all the returned values to be correct, i.e. match the value in the deploy function.

2023-10-08 15:53 UTC, MKdir98 commented
I tried to fix them as much as I could. Please check it again and tell me if it has problem

2023-10-09 11:07 UTC, merged

2023-10-09 11:08 UTC, behrang commented
Good job. Thanks.